Fix dropItemAtPosition
moddio/moddio2 pull request #690
Opened 2023-12-23 01:26 UTC by bruh-9000

2024-01-02 17:40 UTC, sloont requested changes

2024-01-02 17:40 UTC, sloont commented on src/gameClasses/Unit.js
> +					item.teleportTo(position.x, position.y, item._rotate.z);
is there a difference between this rotate value and `item.anchoredOffset.rotate` used above?

2024-01-02 17:40 UTC, sloont commented on src/gameClasses/components/script/ActionComponent.js
> +						}
remove this whitespace and the whitespace on the line below

2024-01-02 17:41 UTC, bruh-9000 commented on src/gameClasses/Unit.js
> +					item.teleportTo(position.x, position.y, item._rotate.z);
Sorry I don't understand what you mean.

2024-01-04 06:50 UTC, bruh-9000 commented on src/gameClasses/Unit.js
> +					item.teleportTo(position.x, position.y, item._rotate.z);
I'm not sure

2024-01-24 17:36 UTC, bruh-9000 commented
@sloont

2024-01-26 16:47 UTC, Grenagar approved these changes

2024-01-26 16:47 UTC, merged