Fix camera moving in non play mode
moddio/moddio2 pull request #703
Opened 2023-12-25 20:44 UTC by bruh-9000

2023-12-25 20:44 UTC, bruh-9000 commented
https://github.com/moddio/moddio2/issues/612

2024-01-02 17:16 UTC, sloont requested changes

2024-01-02 17:16 UTC, sloont commented on src/client.js
> +		if (taro.developerMode.activeTab === "play") {
`taro.developerMode.activeTab` is going to be undefined if the player does not have access to editing game.

2024-01-02 17:18 UTC, bruh-9000 commented on src/client.js
> +		if (taro.developerMode.activeTab === "play") {
So I can just add `|| ... == undefined` ?

2024-01-05 11:01 UTC, Grenagar reviewed
![image](https://github.com/moddio/moddio2/assets/62058278/363c8140-0056-4d28-ac92-38e179418a78)
I suggest to use this for checking (as we use it in another places) also instead of putting check inside client.js maybe will be better idea to put in GameScene.ts

2024-01-05 16:16 UTC, bruh-9000 commented
@Grenagar I noticed though that changing zoom amount was also checked in client.js for being in the play tab, so that's why I assumed it should be in client.js

2024-01-05 16:30 UTC, Grenagar commented
> @Grenagar I noticed though that changing zoom amount was also checked in client.js for being in the play tab, so that's why I assumed it should be in client.js

and 'instant-camera-move' is inside GameScene.ts lets think together where we should place all of them

2024-01-05 16:33 UTC, bruh-9000 commented
I mean we can go with your idea of putting it in gamescene.ts and have them in different places, maybe could leave a comment in client.js about it

2024-01-24 17:41 UTC, bruh-9000 commented
Closing and making new PR

2024-01-24 17:43 UTC, bruh-9000 commented
@Grenagar I'm looking in gamescene.ts and it already is checking for if the player is in play mode?

	taro.client.on('instant-move-camera', (x: number, y: number) => {
			if (!taro.developerMode.active || taro.developerMode.activeTab === 'play') {
			    camera.centerOn(x, y);
			}
		});

2024-01-25 13:03 UTC, Grenagar commented
> @Grenagar I'm looking in gamescene.ts and it already is checking for if the player is in play mode?
> 
> ```
> taro.client.on('instant-move-camera', (x: number, y: number) => {
> 		if (!taro.developerMode.active || taro.developerMode.activeTab === 'play') {
> 		    camera.centerOn(x, y);
> 		}
> 	});
> ```

it check now for 'instant-move-camera', but not for normal 'position-camera'

2024-01-25 16:34 UTC, bruh-9000 commented
> > @Grenagar I'm looking in gamescene.ts and it already is checking for if the player is in play mode?
> > 
> > ```
> > taro.client.on('instant-move-camera', (x: number, y: number) => {
> > 		if (!taro.developerMode.active || taro.developerMode.activeTab === 'play') {
> > 		    camera.centerOn(x, y);
> > 		}
> > 	});
> > ```
> 
> it check now for 'instant-move-camera', but not for normal 'position-camera'

So if I copy the check for instant camera to position camera that should fix it?

2024-01-25 16:56 UTC, Grenagar commented
> > > @Grenagar I'm looking in gamescene.ts and it already is checking for if the player is in play mode?
> > > ```
> > > taro.client.on('instant-move-camera', (x: number, y: number) => {
> > > 		if (!taro.developerMode.active || taro.developerMode.activeTab === 'play') {
> > > 		    camera.centerOn(x, y);
> > > 		}
> > > 	});
> > > ```
> > 
> > 
> > it check now for 'instant-move-camera', but not for normal 'position-camera'
> 
> So if I copy the check for instant camera to position camera that should fix it?

yes, dont forget to run 'npm run tsc' to compile js file

2024-01-27 00:38 UTC, bruh-9000 commented
https://github.com/moddio/moddio2/pull/765

2024-01-27 00:38 UTC, closed without merging