Fix duplicate user name bug
moddio/moddio2 pull request #773
Opened 2024-01-31 19:37 UTC by bruh-9000

https://github.com/moddio/moddio2/pull/675

2024-02-22 17:27 UTC, m0dE commented
please provide rationale behind this PR. I can see some reasons why, but I'd like to hear from you. also plz do this for all future PRs. @bruh-9000

2024-02-22 17:30 UTC, m0dE commented
@sloont please see if you can implement this in clusterServer logic (or should we?)

2024-02-22 18:21 UTC, bruh-9000 commented
@m0dE rationale is that if there are multiple users with the same name, scripts that utilize player names may confuse them to be the same player and have issues. Rare, but possible, I've seen multiple users with the same name before.

2024-03-14 16:55 UTC, sloont commented on server/ServerNetworkEvents.js
> +		var existing_names = taro.$$('player').filter(player => player._stats.controlledBy === 'human').map(player => player._stats.username.substring('user'.length))
this needs to be broken down into more readable code. it's too smart for its own good. on that note, this really needs comments explaining what is happening. chaining two array methods and internally using a string method unnecessarily is hard to follow.

also describe what this array is meant to look like after all of this processing--im guessing its an array of multiple `undefined` and guest user numbers

2024-03-14 16:55 UTC, sloont requested changes

2024-03-14 16:55 UTC, sloont commented on server/ServerNetworkEvents.js
> +			do {
this is good though. comment though pls

2024-03-15 01:07 UTC, closed without merging